### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by henild** [cythron/PsvRepair#1]
OS: Window 10

It is giving me an error "Could not load file or assemble Ookii.Dialogs.WinForm".
I tried googling it and found a git repo of it. But not being familiar to C#. I am not able to install it.

**Comment by cythron** [comment]
Sorry I am uploading it. Please wait a few minutes

**Comment by cythron** [comment]
I am new to Github. I can't seem to upload the release as .zip file.

**Comment by henild** [comment]
No hurry.

**Comment by cythron** [comment]
I have uploaded the binary along with its dependencies as a zip. Please find it in the root of the repo. Note that, it will freeze while repairing the files. So, if you have a large number of files, it will freeze for a few minutes.

**Comment by henild** [comment]
Yeah its working now. Thank You so Much for the fix. Btw I was just curious why did you choose C# to write the fix is it just because it has somethings that other languages don't have?

Again Thank You so much.

**Comment by cythron** [comment]
@Henil 
You're welcome :)

I was panicked after those videos got corrupted. So to make a quick fix, I imported the required classed that I decompiled from Pluralsight Downloader and reused it in C#. Also, I think its easier to code in C#.
